(function (global) {
  "use strict";
  const folders=[{id:"query",name:"Punto consultado"},{id:"cluster",name:"Clúster de análisis"},{id:"projects",name:"Proyectos aprobados utilizados en el análisis"}];
  const localTimestamp=(date=new Date())=>[date.getFullYear(),String(date.getMonth()+1).padStart(2,"0"),String(date.getDate()).padStart(2,"0"),String(date.getHours()).padStart(2,"0"),String(date.getMinutes()).padStart(2,"0"),String(date.getSeconds()).padStart(2,"0")].join("");
  function projectAttributes(item,index){const p=item.feature.properties||{}; return {Orden:index+1,ID:p.id,"Nombre del proyecto":p.nombre_proyecto,Titular:p.titular,Sector:p.sector,Estado:p.estado,Región:p.region,Comuna:p.comuna,Provincia:p.provincia,"Tipo de presentación":p.tipo_presentacion,"Tipo de proyecto":p.tipo_proyecto,Inversión:p.inversion_mmusd,Año:p.anio,"Fecha de presentación":p.fecha_presentacion,"Fecha de calificación":p.fecha_calificacion,"Meses de tramitación":p.meses_tramitacion,"Distancia al punto (km)":item.distance_km.toFixed(6),Web:p.web,Documentación:p.documentacion};}
  function buildKmlState(result){
    const registry=GeoQueryKmlExporter.createKmlExportRegistry(); const style=extra=>GeoQueryKmlExporter.themedStyle("geoeva","line",extra);
    GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:"geoeva-query-point",site:"geoeva",groupId:"general",role:"query-point",folderId:"query",type:"point",name:"Punto consultado",geometry:{type:"Point",coordinates:[result.query.lon,result.query.lat]},style:style({fillOpacity:.95,weight:3}),extendedData:{Latitud:result.query.lat.toFixed(6),Longitud:result.query.lon.toFixed(6)},visible:true});
    if(Number.isFinite(result.radiusMeters)){const geometry=turf.circle([result.query.lon,result.query.lat],result.radiusMeters/1000,{steps:128,units:"kilometers"}).geometry; GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:"geoeva-cluster-circle",site:"geoeva",groupId:"cluster",role:"cluster-circle",folderId:"cluster",type:"polygon",name:"Círculo del clúster de proyectos aprobados",description:"Clúster base definido por los 10 proyectos aprobados más cercanos al punto consultado.",geometry,style:style({weight:3,fill:true,outline:true}),extendedData:{"Cantidad de proyectos base":result.base.length,"Radio del clúster (km)":(result.radiusMeters/1000).toFixed(6),"Sector dominante":result.sectorDominanteCantidad.nombre},visible:true});}
    result.base.forEach((item,index)=>GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:`geoeva-project-${index+1}`,site:"geoeva",groupId:"projects",role:"related-point",folderId:"projects",type:"point",name:`${index+1}. ${item.feature.properties?.nombre_proyecto||"Proyecto aprobado"}`,geometry:{type:"Point",coordinates:[item.lon,item.lat]},style:style({fillOpacity:.9,weight:2,labelScale:.9}),extendedData:projectAttributes(item,index),visible:true}));
    return {site:"geoeva",fileName:`geoeva_Consulta_${localTimestamp()}.kml`,documentName:"GeoQuery | GeoEVA",documentDescription:document.getElementById("summary-text")?.textContent||"",queryPoint:result.query,folders,features:Array.from(registry.values())};
  }
  function pdfState(result,source,basemap){return {status:"resolved",timestamp:new Date().toISOString(),lat:result.query.lat,lon:result.query.lon,queryContext:{queryPoint:result.query,site:"geoeva"},basemap,source:"Parámetro URL",source_geojson:source,analysis_radius_m:result.radiusMeters,base_approved_cluster:result.base,territorial_group:{dominantSector:result.sectorDominanteCantidad.nombre,dominantSectorCount:result.sectorDominanteCantidad.cantidad,dominantSectorShare:result.sectorDominanteCantidad.porcentaje,approvedPairStats:result.approvedPairStats,dominantSectorPairStats:result.dominantQuantityPairStats,approvedPointRelationStats:result.approvedPointStats,dominantSectorPointRelationStats:result.dominantQuantityPointStats},exportState:{pdfEnabled:true}};}
  function initialize(result,options){const state=pdfState(result,options.source,options.basemap); state.mapExport=buildKmlState(result); global.geoQueryState=state; global.__geoevaReportModel=GeoEvaPdfExport.buildGeoEvaPdfModel({state}); GeoEvaPdfExport.bindGeoEvaPdfButtonOnce(); global.geoQueryKmlRefresh=GeoQueryKmlExporter.installGeoQueryKmlButton(()=>global.geoQueryState.mapExport);}
  global.GeoQuery2Exports={initialize,buildKmlState,pdfState};
})(window);
