(function (global) {
  "use strict";
  function labelNode(title, detail) { const node=document.createElement("div"); const strong=document.createElement("strong"); strong.textContent=title; node.append(strong); if(detail){node.append(document.createElement("br"),document.createTextNode(detail));} return node; }
  function render(result, basemap) {
    const map=L.map("map",{scrollWheelZoom:false,zoomSnap:.25}); const osm=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:"&copy; OpenStreetMap"});
    const sat=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:20,attribution:"Tiles &copy; Esri"}); (basemap==="sat"?sat:osm).addTo(map); L.control.layers({OSM:osm,SAT:sat},null,{collapsed:false}).addTo(map); L.control.scale({metric:true,imperial:false}).addTo(map);
    const query=[result.query.lat,result.query.lon]; map.setView(query,10); L.circleMarker(query,{radius:10,color:"#fff",weight:3,fillColor:"#0b5f55",fillOpacity:1}).addTo(map).bindPopup(labelNode("Punto consultado","WGS84 / EPSG:4326"));
    result.base.forEach((item,index)=>L.marker([item.lat,item.lon],{icon:L.divIcon({className:"project-number-label",html:`<span>${index+1}</span>`,iconSize:null,iconAnchor:[7,7]})}).addTo(map).bindPopup(labelNode(String(item.feature.properties?.nombre_proyecto||"Proyecto"),`${GeoQueryAnalysis.normalizeSector(item.feature.properties?.sector)} · ${GeoQueryRender.km(item.distance_km)}`)));
    const circle=Number.isFinite(result.radiusMeters)?L.circle(query,{radius:result.radiusMeters,color:"#0b5f55",weight:2,fillColor:"#0b5f55",fillOpacity:.08}).addTo(map):null;
    if(result.base.length){ const center=[result.base.reduce((s,p)=>s+p.lat,0)/result.base.length,result.base.reduce((s,p)=>s+p.lon,0)/result.base.length]; L.circleMarker(center,{radius:7,color:"#503d78",weight:2,fillColor:"#fff",fillOpacity:1}).addTo(map).bindTooltip("Centroide visual del grupo"); const nearest=result.base[0]; L.polyline([query,[nearest.lat,nearest.lon]],{color:"#d97706",dashArray:"7 6",weight:2}).addTo(map).bindTooltip(`Proyecto más cercano: ${GeoQueryRender.km(nearest.distance_km)}`); }
    const legend=L.control({position:"bottomright"}); legend.onAdd=()=>{const div=L.DomUtil.create("div","map-legend"); [["query","Punto consultado"],["project","Proyecto aprobado"],["centroid","Centroide visual"]].forEach(([c,t])=>{const row=document.createElement("div"); const dot=document.createElement("i"); dot.className=c; row.append(dot,document.createTextNode(t)); div.appendChild(row);}); return div;}; legend.addTo(map);
    if(circle) map.fitBounds(circle.getBounds(),{padding:[20,20]}); else map.setView(query,10); requestAnimationFrame(()=>map.invalidateSize()); enableTouchGuard(map,map.getContainer()); return map;
  }
  function enableTouchGuard(map,container){if(!matchMedia("(pointer: coarse)").matches&&!navigator.maxTouchPoints)return; map.dragging.disable(); const hint=document.createElement("span"); hint.className="touch-hint"; hint.textContent="Usa dos dedos para mover el mapa"; container.appendChild(hint); container.addEventListener("touchstart",e=>{const two=e.touches.length>1; two?map.dragging.enable():map.dragging.disable(); hint.classList.toggle("visible",!two);},{passive:true}); container.addEventListener("touchend",()=>{map.dragging.disable();hint.classList.remove("visible");},{passive:true});}
  global.GeoQueryMap={render};
})(window);
