(function () {
  "use strict";
  const MAX_LIMIT=20,CATALOG_URL="../capas_geoquery/catalogo.json";
  let currentLimit=5,allResults=[],displayLayers=[],containingCircle=null,setBounds=null;
  const params=new URLSearchParams(location.search),queryLat=Number(params.get("lat")??params.get("queryLat")),queryLon=Number(params.get("lon")??params.get("queryLon")),requestedZoom=Number(params.get("zoom")),requestedBasemap=String(params.get("basemap")||"osm").toLowerCase()==="sat"?"sat":"osm";
  const validPoint=Number.isFinite(queryLat)&&queryLat>=-90&&queryLat<=90&&Number.isFinite(queryLon)&&queryLon>=-180&&queryLon<=180;
  const els={status:document.getElementById("query-status"),count:document.getElementById("water-count"),nearest:document.getElementById("nearest-distance"),lat:document.getElementById("latitude"),lon:document.getElementById("longitude"),coords:document.getElementById("decimal-coordinates"),list:document.getElementById("nearest-list"),listTitle:document.getElementById("list-title"),mapDescription:document.getElementById("map-description"),criterion:document.getElementById("current-criterion"),fit:document.getElementById("fit-set-button")};
  els.lat.textContent=validPoint?queryLat.toFixed(6):"No disponible";els.lon.textContent=validPoint?queryLon.toFixed(6):"No disponible";els.coords.textContent=validPoint?`${queryLat.toFixed(6)}, ${queryLon.toFixed(6)}`:"No disponible";
  const map=L.map("geoquery-map",{zoomControl:true,minZoom:3}),basemaps={osm:L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}),sat:L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"Tiles &copy; Esri"})};
  let activeBasemap=requestedBasemap;basemaps[activeBasemap].addTo(map);L.control.scale({position:"bottomleft",imperial:false}).addTo(map);
  function setBasemap(name){if(!basemaps[name]||name===activeBasemap)return;map.removeLayer(basemaps[activeBasemap]);activeBasemap=name;basemaps[name].addTo(map);["osm","sat"].forEach(id=>{const b=document.getElementById(`btn-${id}`),a=id===name;b.classList.toggle("active",a);b.setAttribute("aria-pressed",String(a))})}
  document.getElementById("btn-osm").onclick=()=>setBasemap("osm");document.getElementById("btn-sat").onclick=()=>setBasemap("sat");setTimeout(()=>setBasemap(activeBasemap),0);
  map.setView(validPoint?[queryLat,queryLon]:[-41.47,-72.94],validPoint&&Number.isFinite(requestedZoom)?Math.max(3,Math.min(16,requestedZoom)):7);
  let queryMarker=null;if(validPoint)queryMarker=L.circleMarker([queryLat,queryLon],{radius:8,color:"#102a43",weight:3,fillColor:"#38bdf8",fillOpacity:1}).addTo(map).bindPopup(`<strong>Punto consultado</strong><br>${queryLat.toFixed(6)}, ${queryLon.toFixed(6)}`);
  function lonLatToMercator(lon,lat){const x=lon*20037508.34/180;let y=Math.log(Math.tan((90+lat)*Math.PI/360))/(Math.PI/180);return[x,y*20037508.34/180]}
  function mercatorToLonLat(x,y){const lon=x/20037508.34*180;let lat=y/20037508.34*180;lat=180/Math.PI*(2*Math.atan(Math.exp(lat*Math.PI/180))-Math.PI/2);return[lon,lat]}
  const queryMercator=validPoint?lonLatToMercator(queryLon,queryLat):null,scale=validPoint?Math.cos(queryLat*Math.PI/180):1;
  function pointInRing(p,r){let inside=false,x=p[0],y=p[1];for(let i=0,j=r.length-1;i<r.length;j=i++){const xi=+r[i][0],yi=+r[i][1],xj=+r[j][0],yj=+r[j][1];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/((yj-yi)||Number.EPSILON)+xi))inside=!inside}return inside}
  function pointInPolygon(p,r){if(!r?.length||!pointInRing(p,r[0]))return false;for(let i=1;i<r.length;i++)if(pointInRing(p,r[i]))return false;return true}
  function sqSeg(p,a,b){const px=p[0],py=p[1],ax=+a[0],ay=+a[1],bx=+b[0],by=+b[1],dx=bx-ax,dy=by-ay;if(!dx&&!dy)return(px-ax)**2+(py-ay)**2;const t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy))),x=ax+t*dx,y=ay+t*dy;return(px-x)**2+(py-y)**2}
  function polygonDistance(p,rings){if(pointInPolygon(p,rings))return 0;let m=Infinity;for(const r of rings||[]){for(let i=1;i<r.length;i++)m=Math.min(m,sqSeg(p,r[i-1],r[i]));if(r.length>2)m=Math.min(m,sqSeg(p,r[r.length-1],r[0]))}return Math.sqrt(m)*scale}
  function geometryDistance(g){if(!g)return Infinity;if(g.type==="Polygon")return polygonDistance(queryMercator,g.coordinates);if(g.type==="MultiPolygon")return Math.min(...g.coordinates.map(p=>polygonDistance(queryMercator,p)));return Infinity}
  function bboxDistance(b){if(!Array.isArray(b)||b.length<4)return Infinity;const[w,s,e,n]=b.map(Number),clon=Math.max(w,Math.min(e,queryLon)),clat=Math.max(s,Math.min(n,queryLat)),ml=(queryLat+clat)*Math.PI/360;return Math.hypot((queryLon-clon)*111320*Math.cos(ml),(queryLat-clat)*110540)}
  function transform(c){if(!Array.isArray(c))return c;if(c.length>=2&&typeof c[0]==="number"&&typeof c[1]==="number")return mercatorToLonLat(c[0],c[1]);return c.map(transform)}
  function leafletFeature(f){return{type:"Feature",properties:f.properties||{},geometry:f.geometry?{...f.geometry,coordinates:transform(f.geometry.coordinates)}:null}}
  function label(f){const p=f.properties||{},n=String(p.Nombre||"").trim(),t=String(p.Tipo||"Masa de agua").trim()||"Masa de agua",c=String(p.Comuna||"").trim();return n||[t,c].filter(Boolean).join(" – ")||"Masa de agua sin nombre"}
  function fmtDist(m){if(!Number.isFinite(m))return"—";return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(m<10000?1:0)} km`}
  function fmtArea(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)return"Superficie s/i";const ha=n/10000;return`${new Intl.NumberFormat("es-CL",{maximumFractionDigits:ha<10?1:0}).format(ha)} ha`}
  async function loadRegion(r){const u=`../capas_geoquery/${encodeURIComponent(r.file).replace(/%2F/g,"/")}`,res=await fetch(u,{cache:"no-store"});if(!res.ok)throw new Error(`${r.region}: HTTP ${res.status}`);const g=await res.json();return Array.isArray(g.features)?g.features:[]}
  async function findNearest(catalog){const regions=(catalog.layers||[]).filter(l=>l.enabled!==false).map(l=>({...l,bboxDistance:bboxDistance(l.bbox)})).sort((a,b)=>a.bboxDistance-b.bboxDistance),nearest=[];for(const region of regions){const cutoff=nearest.length>=MAX_LIMIT?nearest[MAX_LIMIT-1].distance:Infinity;if(nearest.length>=MAX_LIMIT&&region.bboxDistance>cutoff)break;els.status.textContent=`Analizando ${region.region}…`;for(const feature of await loadRegion(region)){const distance=geometryDistance(feature.geometry);if(Number.isFinite(distance))nearest.push({feature,distance,region:region.region})}nearest.sort((a,b)=>a.distance-b.distance);if(nearest.length>MAX_LIMIT)nearest.length=MAX_LIMIT}return nearest}
  function clearDisplay(){displayLayers.forEach(l=>map.removeLayer(l));displayLayers=[];if(containingCircle){map.removeLayer(containingCircle);containingCircle=null}}
  function fitSet(){if(setBounds&&setBounds.isValid())map.fitBounds(setBounds.pad(.08),{maxZoom:12})}
  function render(){clearDisplay();const results=allResults.slice(0,currentLimit);els.count.textContent=String(results.length);els.nearest.textContent=results.length?fmtDist(results[0].distance):"—";els.listTitle.textContent=`${results.length} más cercanas`;els.mapDescription.textContent=`El mapa encuadra el punto consultado y las ${results.length} masas de agua con menor distancia al borde.`;els.criterion.textContent=`${results.length} masas de agua más cercanas`;els.list.innerHTML="";const group=L.featureGroup();if(queryMarker)group.addLayer(queryMarker);
    results.forEach((item,index)=>{const p=item.feature.properties||{},name=label(item.feature),layer=L.geoJSON(leafletFeature(item.feature),{style:{color:"#0284c7",weight:2.5,opacity:1,fillColor:"#38bdf8",fillOpacity:.24}}).addTo(map);displayLayers.push(layer);layer.bindTooltip(`${index+1}. ${name}`,{sticky:true,className:"water-tooltip"});group.addLayer(layer);const row=document.createElement("div");row.className="nearest-item";row.tabIndex=0;row.innerHTML=`<span class="nearest-rank">${String(index+1).padStart(2,"0")}</span><span class="nearest-main"><strong class="nearest-name"></strong><span class="nearest-meta"></span></span><strong class="nearest-distance">${fmtDist(item.distance)}</strong>`;row.querySelector(".nearest-name").textContent=name;row.querySelector(".nearest-meta").textContent=[p.Tipo||"Masa de agua",p.Comuna||"Comuna s/i",fmtArea(p.st_area_sh)].join(" · ");const hi=a=>{row.classList.toggle("is-active",a);layer.setStyle(a?{color:"#102a43",weight:4,fillOpacity:.38}:{color:"#0284c7",weight:2.5,fillOpacity:.24});if(a)layer.bringToFront()};row.onmouseenter=()=>hi(true);row.onmouseleave=()=>hi(false);row.onfocus=()=>hi(true);row.onblur=()=>hi(false);row.onclick=()=>{const b=layer.getBounds();if(b.isValid())map.fitBounds(b.pad(.25),{maxZoom:14})};els.list.appendChild(row)});
    if(results.length){const radius=results[results.length-1].distance;if(Number.isFinite(radius)&&radius>0){containingCircle=L.circle([queryLat,queryLon],{radius,color:"#0f172a",weight:2,opacity:.75,dashArray:"8 6",fillColor:"#38bdf8",fillOpacity:.035,interactive:false}).addTo(map);containingCircle.bringToBack();group.addLayer(containingCircle)}}setBounds=group.getBounds();fitSet();els.status.textContent=results.length?`Consulta lista · ${results.length} masas de agua más cercanas`:"No se encontraron masas de agua para esta consulta."}
  document.querySelectorAll('input[name="nearest-limit"]').forEach(r=>r.addEventListener("change",()=>{currentLimit=Number(r.value);render()}));els.fit.addEventListener("click",fitSet);
  async function init(){if(!validPoint){els.status.textContent="No se recibió un punto de consulta válido.";return}try{const r=await fetch(CATALOG_URL,{cache:"no-store"});if(!r.ok)throw new Error(`Catálogo GeoQuery no disponible (HTTP ${r.status})`);allResults=await findNearest(await r.json());render()}catch(e){console.error("[GeoMA GeoQuery]",e);els.status.textContent="No fue posible cargar las capas de GeoQuery.";els.list.innerHTML='<p class="placeholder-text">Revise que <strong>geoma/capas_geoquery</strong> esté disponible y vuelva a intentar.</p>'}}
  document.getElementById("back-link").addEventListener("click",e=>{if(history.length>1&&document.referrer){e.preventDefault();history.back()}});init();
})();
