(function(){
  "use strict";
  const MAX_LIMIT=20,CATALOG_URL="../capas_geoquery/catalogo.json",KML_COLOR="#00E5FF";
  const params=new URLSearchParams(location.search),queryLat=Number(params.get("lat")??params.get("queryLat")),queryLon=Number(params.get("lon")??params.get("queryLon"));
  const validPoint=Number.isFinite(queryLat)&&queryLat>=-90&&queryLat<=90&&Number.isFinite(queryLon)&&queryLon>=-180&&queryLon<=180;
  const queryMercator=validPoint?lonLatToMercator(queryLon,queryLat):null,scale=validPoint?Math.cos(queryLat*Math.PI/180):1;
  let allResults=[],ready=false;

  function lonLatToMercator(lon,lat){const x=lon*20037508.34/180;let y=Math.log(Math.tan((90+lat)*Math.PI/360))/(Math.PI/180);return[x,y*20037508.34/180]}
  function mercatorToLonLat(x,y){const lon=x/20037508.34*180;let lat=y/20037508.34*180;lat=180/Math.PI*(2*Math.atan(Math.exp(lat*Math.PI/180))-Math.PI/2);return[lon,lat]}
  function transform(c){if(!Array.isArray(c))return c;if(c.length>=2&&typeof c[0]==="number"&&typeof c[1]==="number")return mercatorToLonLat(c[0],c[1]);return c.map(transform)}
  function pointInRing(p,r){let inside=false,x=p[0],y=p[1];for(let i=0,j=r.length-1;i<r.length;j=i++){const xi=+r[i][0],yi=+r[i][1],xj=+r[j][0],yj=+r[j][1];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/((yj-yi)||Number.EPSILON)+xi))inside=!inside}return inside}
  function pointInPolygon(p,r){if(!r?.length||!pointInRing(p,r[0]))return false;for(let i=1;i<r.length;i++)if(pointInRing(p,r[i]))return false;return true}
  function nearestOnSeg(p,a,b){const px=p[0],py=p[1],ax=+a[0],ay=+a[1],bx=+b[0],by=+b[1],dx=bx-ax,dy=by-ay;if(!dx&&!dy)return{point:[ax,ay],sq:(px-ax)**2+(py-ay)**2};const t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy))),x=ax+t*dx,y=ay+t*dy;return{point:[x,y],sq:(px-x)**2+(py-y)**2}}
  function nearestOnPolygon(p,rings){if(pointInPolygon(p,rings))return{distance:0,point:p};let best={distance:Infinity,point:null};for(const r of rings||[]){for(let i=1;i<r.length;i++){const q=nearestOnSeg(p,r[i-1],r[i]);if(q.sq<best.distance){best={distance:q.sq,point:q.point}}}if(r.length>2){const q=nearestOnSeg(p,r[r.length-1],r[0]);if(q.sq<best.distance)best={distance:q.sq,point:q.point}}}return{distance:Math.sqrt(best.distance)*scale,point:best.point}}
  function geometryNearest(g){if(!g)return{distance:Infinity,point:null};if(g.type==="Polygon")return nearestOnPolygon(queryMercator,g.coordinates);if(g.type==="MultiPolygon"){let best={distance:Infinity,point:null};for(const p of g.coordinates){const q=nearestOnPolygon(queryMercator,p);if(q.distance<best.distance)best=q}return best}return{distance:Infinity,point:null}}
  function bboxDistance(b){if(!Array.isArray(b)||b.length<4)return Infinity;const[w,s,e,n]=b.map(Number),clon=Math.max(w,Math.min(e,queryLon)),clat=Math.max(s,Math.min(n,queryLat)),ml=(queryLat+clat)*Math.PI/360;return Math.hypot((queryLon-clon)*111320*Math.cos(ml),(queryLat-clat)*110540)}
  async function loadRegion(r){const u=`../capas_geoquery/${encodeURIComponent(r.file).replace(/%2F/g,"/")}`,res=await fetch(u,{cache:"force-cache"});if(!res.ok)throw new Error(`${r.region}: HTTP ${res.status}`);const g=await res.json();return Array.isArray(g.features)?g.features:[]}
  async function findNearest(catalog){const regions=(catalog.layers||[]).filter(l=>l.enabled!==false).map(l=>({...l,bboxDistance:bboxDistance(l.bbox)})).sort((a,b)=>a.bboxDistance-b.bboxDistance),nearest=[];for(const region of regions){const cutoff=nearest.length>=MAX_LIMIT?nearest[MAX_LIMIT-1].distance:Infinity;if(nearest.length>=MAX_LIMIT&&region.bboxDistance>cutoff)break;for(const feature of await loadRegion(region)){const near=geometryNearest(feature.geometry);if(Number.isFinite(near.distance))nearest.push({feature,distance:near.distance,nearestPoint:near.point,region:region.region})}nearest.sort((a,b)=>a.distance-b.distance);if(nearest.length>MAX_LIMIT)nearest.length=MAX_LIMIT}return nearest}
  function currentLimit(){return Number(document.querySelector('input[name="nearest-limit"]:checked')?.value)||5}
  function circleGeometry(radiusMeters,steps=128){const coords=[];for(let i=0;i<=steps;i++){const a=2*Math.PI*i/steps,x=queryMercator[0]+Math.cos(a)*(radiusMeters/scale),y=queryMercator[1]+Math.sin(a)*(radiusMeters/scale),ll=mercatorToLonLat(x,y);coords.push(ll)}return{type:"Polygon",coordinates:[coords]}}
  function averageVector(results){if(!results.length)return null;let sx=0,sy=0,n=0;for(const item of results){const p=item.nearestPoint;if(!p)continue;const dx=p[0]-queryMercator[0],dy=p[1]-queryMercator[1],len=Math.hypot(dx,dy);if(len>0){sx+=dx/len;sy+=dy/len;n++}}if(!n)return null;const meanDist=results.reduce((s,x)=>s+x.distance,0)/results.length,len=Math.hypot(sx,sy);if(!len||!Number.isFinite(meanDist))return null;const ux=sx/len,uy=sy/len,endMerc=[queryMercator[0]+ux*(meanDist/scale),queryMercator[1]+uy*(meanDist/scale)];return{meanDist,endpoint:mercatorToLonLat(endMerc[0],endMerc[1])}}
  function label(f){const p=f.properties||{},n=String(p.Nombre||"").trim(),t=String(p.Tipo||"Masa de agua").trim()||"Masa de agua",c=String(p.Comuna||"").trim();return n||[t,c].filter(Boolean).join(" – ")||"Masa de agua sin nombre"}
  function localTimestamp(date=new Date()){return[date.getFullYear(),String(date.getMonth()+1).padStart(2,"0"),String(date.getDate()).padStart(2,"0"),String(date.getHours()).padStart(2,"0"),String(date.getMinutes()).padStart(2,"0"),String(date.getSeconds()).padStart(2,"0")].join("")}
  function style(extra={}){return{color:KML_COLOR,fillColor:KML_COLOR,opacity:1,fillOpacity:.18,weight:3,labelColor:KML_COLOR,labelScale:.9,...extra}}
  function buildState(){const results=allResults.slice(0,currentLimit()),registry=GeoQueryKmlExporter.createKmlExportRegistry(),radius=results.length?results[results.length-1].distance:NaN,vector=averageVector(results),folders=[{id:"query",name:"Punto consultado"},{id:"cluster",name:"Geometría del conjunto"},{id:"waters",name:"Masas de agua seleccionadas"}];
    GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:"geoma-query",site:"geoma",groupId:"general",role:"query-point",folderId:"query",type:"point",name:"Punto consultado",geometry:{type:"Point",coordinates:[queryLon,queryLat]},style:style({fillOpacity:1,weight:3,iconScale:1.1}),extendedData:{Latitud:queryLat.toFixed(6),Longitud:queryLon.toFixed(6)},visible:true});
    if(Number.isFinite(radius)&&radius>0)GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:"geoma-container-circle",site:"geoma",groupId:"cluster",role:"cluster-circle",folderId:"cluster",type:"polygon",name:`Círculo contenedor · ${results.length} masas`,description:"Círculo contenedor definido por la distancia al borde de la masa seleccionada más lejana.",geometry:circleGeometry(radius),style:style({fillOpacity:.07,weight:3,fill:true,outline:true}),extendedData:{"Cantidad de masas":results.length,"Radio (km)":(radius/1000).toFixed(3)},visible:true});
    if(vector)GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:"geoma-mean-distance-vector",site:"geoma",groupId:"cluster",role:"mean-distance",folderId:"cluster",type:"line",name:"Vector de distancia media al POI",description:"Vector orientado hacia la dirección media de las masas seleccionadas y con longitud igual a la distancia media borde–POI.",geometry:{type:"LineString",coordinates:[[queryLon,queryLat],vector.endpoint]},style:style({weight:5,fill:false}),extendedData:{"Distancia media (km)":(vector.meanDist/1000).toFixed(3)},visible:true});
    results.forEach((item,index)=>{const p=item.feature.properties||{};GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:`geoma-water-${index+1}`,site:"geoma",groupId:"waters",role:"water-polygon",folderId:"waters",type:String(item.feature.geometry?.type||"").toLowerCase()==="multipolygon"?"multipolygon":"polygon",name:`${index+1}. ${label(item.feature)}`,description:`${p.Tipo||"Masa de agua"}${p.Comuna?` · ${p.Comuna}`:""}`,geometry:{type:item.feature.geometry.type,coordinates:transform(item.feature.geometry.coordinates)},style:style({fillOpacity:.22,weight:3,fill:true,outline:true}),extendedData:{Orden:index+1,Tipo:p.Tipo||"",Nombre:p.Nombre||"",Comuna:p.Comuna||"","Superficie (ha)":Number.isFinite(Number(p.st_area_sh))?(Number(p.st_area_sh)/10000).toFixed(2):"","Distancia al POI (km)":(item.distance/1000).toFixed(3)},visible:true})});
    return{site:"geoma",fileName:`GeoMA_Consulta_${localTimestamp()}.kml`,documentName:"GeoQuery | GeoMA",documentDescription:`Consulta territorial de ${results.length} masas de agua más cercanas.`,queryPoint:{lat:queryLat,lon:queryLon},folders,features:Array.from(registry.values())}}
  function refresh(){if(!ready)return;window.geoQueryState=window.geoQueryState||{};window.geoQueryState.mapExport=buildState();if(typeof window.geoQueryKmlRefresh==="function")window.geoQueryKmlRefresh()}
  async function init(){if(!validPoint||!window.GeoQueryKmlExporter)return;try{const r=await fetch(CATALOG_URL,{cache:"force-cache"});if(!r.ok)throw new Error(`Catálogo HTTP ${r.status}`);allResults=await findNearest(await r.json());ready=true;window.geoQueryState=window.geoQueryState||{};window.geoQueryState.mapExport=buildState();window.geoQueryKmlRefresh=GeoQueryKmlExporter.installGeoQueryKmlButton(()=>{refresh();return window.geoQueryState.mapExport});document.querySelectorAll('input[name="nearest-limit"]').forEach(el=>el.addEventListener("change",refresh))}catch(e){console.error("[GeoMA KML]",e)}}
  init();
})();
