(function () {
  "use strict";
  const MAX_LIMIT=20,CATALOG_URL="../capas_geoquery/catalogo.json",BLUE="#0284c7",BLUE_FILL="#38bdf8",DARK="#0f172a",FLUOR="#f5ff00";
  let currentLimit=5,allResults=[],displayLayers=[],containingCircle=null,radiusLine=null,radiusLabel=null,setBounds=null;
  const params=new URLSearchParams(location.search),queryLat=Number(params.get("lat")??params.get("queryLat")),queryLon=Number(params.get("lon")??params.get("queryLon")),requestedZoom=Number(params.get("zoom")),requestedBasemap=String(params.get("basemap")||"osm").toLowerCase()==="sat"?"sat":"osm";
  const validPoint=Number.isFinite(queryLat)&&queryLat>=-90&&queryLat<=90&&Number.isFinite(queryLon)&&queryLon>=-180&&queryLon<=180;
  function buildReturnUrl(){const back=new URLSearchParams(),keys=["lat","lon","queryLat","queryLon","viewLat","viewLon","mapCenterLat","mapCenterLon","zoom","mapZoom","basemap","viewWest","viewSouth","viewEast","viewNorth","restoreViewport"];keys.forEach(key=>{if(params.has(key))back.set(key,params.get(key))});back.set("from",params.get("from")==="crossaccess"?"crossaccess":"geoquery");back.set("restoreViewport","1");return `../index.html?${back.toString()}`}
  const els={status:document.getElementById("query-status"),count:document.getElementById("water-count"),nearest:document.getElementById("nearest-distance"),lat:document.getElementById("latitude"),lon:document.getElementById("longitude"),coords:document.getElementById("decimal-coordinates"),list:document.getElementById("nearest-list"),listTitle:document.getElementById("list-title"),mapDescription:document.getElementById("map-description"),criterion:document.getElementById("current-criterion"),fit:document.getElementById("fit-set-button"),totalArea:document.getElementById("total-area"),equivDiameter:document.getElementById("equivalent-diameter"),meanPoiDistance:document.getElementById("mean-poi-distance"),meanWaterDistance:document.getElementById("mean-water-distance")};
  els.lat.textContent=validPoint?queryLat.toFixed(6):"No disponible";els.lon.textContent=validPoint?queryLon.toFixed(6):"No disponible";els.coords.textContent=validPoint?`${queryLat.toFixed(6)}, ${queryLon.toFixed(6)}`:"No disponible";
  const map=L.map("geoquery-map",{zoomControl:true,minZoom:3}),basemaps={osm:L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}),sat:L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"Tiles &copy; Esri"})};
  let activeBasemap=requestedBasemap;basemaps[activeBasemap].addTo(map);L.control.scale({position:"bottomleft",imperial:false}).addTo(map);
  function baseStyle(active=false){if(activeBasemap==="sat")return{color:FLUOR,weight:active?4:2.5,opacity:1,fillColor:FLUOR,fillOpacity:active?.34:.16};return active?{color:DARK,weight:4,fillColor:BLUE_FILL,fillOpacity:.38}:{color:BLUE,weight:2.5,opacity:1,fillColor:BLUE_FILL,fillOpacity:.24}}
  function updateSymbology(){displayLayers.forEach(l=>l.setStyle(baseStyle(false)));if(containingCircle)containingCircle.setStyle(activeBasemap==="sat"?{color:FLUOR,fillColor:FLUOR,fillOpacity:.025}:{color:DARK,fillColor:BLUE_FILL,fillOpacity:.035});if(radiusLine)radiusLine.setStyle({color:activeBasemap==="sat"?FLUOR:DARK});if(radiusLabel){const el=radiusLabel.getElement();if(el)el.classList.toggle("sat-radius-label",activeBasemap==="sat")}if(queryMarker)queryMarker.setStyle(activeBasemap==="sat"?{color:FLUOR,fillColor:FLUOR}:{color:DARK,fillColor:BLUE_FILL})}
  function setBasemap(name){if(!basemaps[name])return;if(name!==activeBasemap){map.removeLayer(basemaps[activeBasemap]);activeBasemap=name;basemaps[name].addTo(map)}["osm","sat"].forEach(id=>{const b=document.getElementById(`btn-${id}`),a=id===activeBasemap;b.classList.toggle("active",a);b.setAttribute("aria-pressed",String(a))});updateSymbology()}
  document.getElementById("btn-osm").onclick=()=>setBasemap("osm");document.getElementById("btn-sat").onclick=()=>setBasemap("sat");
  map.setView(validPoint?[queryLat,queryLon]:[-41.47,-72.94],validPoint&&Number.isFinite(requestedZoom)?Math.max(3,Math.min(16,requestedZoom)):7);
  let queryMarker=null;if(validPoint)queryMarker=L.circleMarker([queryLat,queryLon],{radius:8,color:DARK,weight:3,fillColor:BLUE_FILL,fillOpacity:1}).addTo(map).bindPopup(`<strong>Punto consultado</strong><br>${queryLat.toFixed(6)}, ${queryLon.toFixed(6)}`);
  function lonLatToMercator(lon,lat){const x=lon*20037508.34/180;let y=Math.log(Math.tan((90+lat)*Math.PI/360))/(Math.PI/180);return[x,y*20037508.34/180]}
  function mercatorToLonLat(x,y){const lon=x/20037508.34*180;let lat=y/20037508.34*180;lat=180/Math.PI*(2*Math.atan(Math.exp(lat*Math.PI/180))-Math.PI/2);return[lon,lat]}
  const queryMercator=validPoint?lonLatToMercator(queryLon,queryLat):null,scale=validPoint?Math.cos(queryLat*Math.PI/180):1;
  function pointInRing(p,r){let inside=false,x=p[0],y=p[1];for(let i=0,j=r.length-1;i<r.length;j=i++){const xi=+r[i][0],yi=+r[i][1],xj=+r[j][0],yj=+r[j][1];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/((yj-yi)||Number.EPSILON)+xi))inside=!inside}return inside}
  function pointInPolygon(p,r){if(!r?.length||!pointInRing(p,r[0]))return false;for(let i=1;i<r.length;i++)if(pointInRing(p,r[i]))return false;return true}
  function sqSeg(p,a,b){const px=p[0],py=p[1],ax=+a[0],ay=+a[1],bx=+b[0],by=+b[1],dx=bx-ax,dy=by-ay;if(!dx&&!dy)return(px-ax)**2+(py-ay)**2;const t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy))),x=ax+t*dx,y=ay+t*dy;return(px-x)**2+(py-y)**2}
  function polygonDistance(p,rings){if(pointInPolygon(p,rings))return 0;let m=Infinity;for(const r of rings||[]){for(let i=1;i<r.length;i++)m=Math.min(m,sqSeg(p,r[i-1],r[i]));if(r.length>2)m=Math.min(m,sqSeg(p,r[r.length-1],r[0]))}return Math.sqrt(m)*scale}
  function geometryDistance(g){if(!g)return Infinity;if(g.type==="Polygon")return polygonDistance(queryMercator,g.coordinates);if(g.type==="MultiPolygon")return Math.min(...g.coordinates.map(p=>polygonDistance(queryMercator,p)));return Infinity}
  function polygonsOf(g){if(!g)return[];if(g.type==="Polygon")return[g.coordinates];if(g.type==="MultiPolygon")return g.coordinates;return[]}
  function segmentsOf(g){const out=[];for(const poly of polygonsOf(g))for(const ring of poly||[]){for(let i=1;i<ring.length;i++)out.push([ring[i-1],ring[i]]);if(ring.length>2)out.push([ring[ring.length-1],ring[0]])}return out}
  function orient(a,b,c){const v=(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);return Math.abs(v)<1e-9?0:(v>0?1:-1)}
  function onSeg(a,b,p){return p[0]>=Math.min(a[0],b[0])-1e-9&&p[0]<=Math.max(a[0],b[0])+1e-9&&p[1]>=Math.min(a[1],b[1])-1e-9&&p[1]<=Math.max(a[1],b[1])+1e-9}
  function segIntersects(a,b,c,d){const o1=orient(a,b,c),o2=orient(a,b,d),o3=orient(c,d,a),o4=orient(c,d,b);if(o1!==o2&&o3!==o4)return true;return(o1===0&&onSeg(a,b,c))||(o2===0&&onSeg(a,b,d))||(o3===0&&onSeg(c,d,a))||(o4===0&&onSeg(c,d,b))}
  function segDistance(a,b,c,d){if(segIntersects(a,b,c,d))return 0;return Math.sqrt(Math.min(sqSeg(a,c,d),sqSeg(b,c,d),sqSeg(c,a,b),sqSeg(d,a,b)))*scale}
  function geometryPairDistance(g1,g2){const p1=polygonsOf(g1),p2=polygonsOf(g2);for(const a of p1)for(const b of p2){if(a?.[0]?.[0]&&pointInPolygon(a[0][0],b))return 0;if(b?.[0]?.[0]&&pointInPolygon(b[0][0],a))return 0}const s1=segmentsOf(g1),s2=segmentsOf(g2);let m=Infinity;for(const a of s1)for(const b of s2){const d=segDistance(a[0],a[1],b[0],b[1]);if(d===0)return 0;if(d<m)m=d}return m}
  function bboxDistance(b){if(!Array.isArray(b)||b.length<4)return Infinity;const[w,s,e,n]=b.map(Number),clon=Math.max(w,Math.min(e,queryLon)),clat=Math.max(s,Math.min(n,queryLat)),ml=(queryLat+clat)*Math.PI/360;return Math.hypot((queryLon-clon)*111320*Math.cos(ml),(queryLat-clat)*110540)}
  function transform(c){if(!Array.isArray(c))return c;if(c.length>=2&&typeof c[0]==="number"&&typeof c[1]==="number")return mercatorToLonLat(c[0],c[1]);return c.map(transform)}
  function leafletFeature(f){return{type:"Feature",properties:f.properties||{},geometry:f.geometry?{...f.geometry,coordinates:transform(f.geometry.coordinates)}:null}}
  function label(f){const p=f.properties||{},n=String(p.Nombre||"").trim(),t=String(p.Tipo||"Masa de agua").trim()||"Masa de agua",c=String(p.Comuna||"").trim();return n||[t,c].filter(Boolean).join(" – ")||"Masa de agua sin nombre"}
  function fmtDist(m){if(!Number.isFinite(m))return"—";return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(m<10000?1:0)} km`}
  function fmtArea(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)return"Superficie s/i";const ha=n/10000;return`${new Intl.NumberFormat("es-CL",{maximumFractionDigits:ha<10?1:0}).format(ha)} ha`}
  function fmtTotalArea(m2){if(!Number.isFinite(m2)||m2<=0)return"—";const ha=m2/10000;return`${new Intl.NumberFormat("es-CL",{maximumFractionDigits:ha<100?1:0}).format(ha)} ha`}
  function updateGeometryKpis(results){const areas=results.map(x=>Number(x.feature.properties?.st_area_sh)).filter(v=>Number.isFinite(v)&&v>0),totalArea=areas.reduce((a,b)=>a+b,0),meanPoi=results.length?results.reduce((s,x)=>s+x.distance,0)/results.length:NaN;let pairSum=0,pairCount=0;for(let i=0;i<results.length;i++)for(let j=i+1;j<results.length;j++){const d=geometryPairDistance(results[i].feature.geometry,results[j].feature.geometry);if(Number.isFinite(d)){pairSum+=d;pairCount++}}els.totalArea.textContent=fmtTotalArea(totalArea);els.equivDiameter.textContent=totalArea>0?fmtDist(2*Math.sqrt(totalArea/Math.PI)):"—";els.meanPoiDistance.textContent=fmtDist(meanPoi);els.meanWaterDistance.textContent=pairCount?fmtDist(pairSum/pairCount):"—"}
  async function loadRegion(r){const u=`../capas_geoquery/${encodeURIComponent(r.file).replace(/%2F/g,"/")}`,res=await fetch(u,{cache:"no-store"});if(!res.ok)throw new Error(`${r.region}: HTTP ${res.status}`);const g=await res.json();return Array.isArray(g.features)?g.features:[]}
  async function findNearest(catalog){const regions=(catalog.layers||[]).filter(l=>l.enabled!==false).map(l=>({...l,bboxDistance:bboxDistance(l.bbox)})).sort((a,b)=>a.bboxDistance-b.bboxDistance),nearest=[];for(const region of regions){const cutoff=nearest.length>=MAX_LIMIT?nearest[MAX_LIMIT-1].distance:Infinity;if(nearest.length>=MAX_LIMIT&&region.bboxDistance>cutoff)break;els.status.textContent=`Analizando ${region.region}…`;for(const feature of await loadRegion(region)){const distance=geometryDistance(feature.geometry);if(Number.isFinite(distance))nearest.push({feature,distance,region:region.region})}nearest.sort((a,b)=>a.distance-b.distance);if(nearest.length>MAX_LIMIT)nearest.length=MAX_LIMIT}return nearest}
  function clearDisplay(){displayLayers.forEach(l=>map.removeLayer(l));displayLayers=[];[containingCircle,radiusLine,radiusLabel].forEach(l=>{if(l)map.removeLayer(l)});containingCircle=radiusLine=radiusLabel=null}
  function fitSet(){if(setBounds&&setBounds.isValid())map.fitBounds(setBounds.pad(.08),{maxZoom:12})}
  function destinationPoint(lat,lon,distance,bearingDeg){const R=6371008.8,b=bearingDeg*Math.PI/180,p1=lat*Math.PI/180,l1=lon*Math.PI/180,d=distance/R,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(b)),l2=l1+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return[p2*180/Math.PI,l2*180/Math.PI]}
  function render(){clearDisplay();const results=allResults.slice(0,currentLimit);els.count.textContent=String(results.length);els.nearest.textContent=results.length?fmtDist(results[0].distance):"—";els.listTitle.textContent=`${results.length} más cercanas`;els.mapDescription.textContent=`El mapa encuadra el punto consultado y las ${results.length} masas de agua con menor distancia al borde.`;els.criterion.textContent=`${results.length} masas de agua más cercanas`;updateGeometryKpis(results);els.list.innerHTML="";const group=L.featureGroup();if(queryMarker)group.addLayer(queryMarker);
    results.forEach((item,index)=>{const p=item.feature.properties||{},name=label(item.feature),layer=L.geoJSON(leafletFeature(item.feature),{style:baseStyle(false)}).addTo(map);displayLayers.push(layer);layer.bindTooltip(`${index+1}. ${name}`,{sticky:true,className:"water-tooltip"});group.addLayer(layer);const row=document.createElement("div");row.className="nearest-item";row.tabIndex=0;row.innerHTML=`<span class="nearest-rank">${String(index+1).padStart(2,"0")}</span><span class="nearest-main"><strong class="nearest-name"></strong><span class="nearest-meta"></span></span><strong class="nearest-distance">${fmtDist(item.distance)}</strong>`;row.querySelector(".nearest-name").textContent=name;row.querySelector(".nearest-meta").textContent=[p.Tipo||"Masa de agua",p.Comuna||"Comuna s/i",fmtArea(p.st_area_sh)].join(" · ");const hi=a=>{row.classList.toggle("is-active",a);layer.setStyle(baseStyle(a));if(a)layer.bringToFront()};row.onmouseenter=()=>hi(true);row.onmouseleave=()=>hi(false);row.onfocus=()=>hi(true);row.onblur=()=>hi(false);row.onclick=()=>{const b=layer.getBounds();if(b.isValid())map.fitBounds(b.pad(.25),{maxZoom:14})};els.list.appendChild(row)});
    if(results.length){const radius=results[results.length-1].distance;if(Number.isFinite(radius)&&radius>0){const c=activeBasemap==="sat"?FLUOR:DARK;containingCircle=L.circle([queryLat,queryLon],{radius,color:c,weight:2,opacity:.9,dashArray:"8 6",fillColor:activeBasemap==="sat"?FLUOR:BLUE_FILL,fillOpacity:activeBasemap==="sat"?.025:.035,interactive:false}).addTo(map);containingCircle.bringToBack();group.addLayer(containingCircle);const edge=destinationPoint(queryLat,queryLon,radius,45),mid=destinationPoint(queryLat,queryLon,radius/2,45);radiusLine=L.polyline([[queryLat,queryLon],edge],{color:c,weight:2,opacity:.95,dashArray:"5 6",interactive:false}).addTo(map);radiusLabel=L.tooltip({permanent:true,direction:"center",className:`radius-label${activeBasemap==="sat"?" sat-radius-label":""}`,interactive:false}).setLatLng(mid).setContent(`R = ${fmtDist(radius)}`).addTo(map);group.addLayer(radiusLine);group.addLayer(radiusLabel)}}setBounds=group.getBounds();fitSet();updateSymbology();els.status.textContent=results.length?`Consulta lista · ${results.length} masas de agua más cercanas`:"No se encontraron masas de agua para esta consulta."}
  document.querySelectorAll('input[name="nearest-limit"]').forEach(r=>r.addEventListener("change",()=>{currentLimit=Number(r.value);render()}));els.fit.addEventListener("click",fitSet);
  async function init(){if(!validPoint){els.status.textContent="No se recibió un punto de consulta válido.";return}try{const r=await fetch(CATALOG_URL,{cache:"no-store"});if(!r.ok)throw new Error(`Catálogo GeoQuery no disponible (HTTP ${r.status})`);allResults=await findNearest(await r.json());render();setBasemap(activeBasemap)}catch(e){console.error("[GeoMA GeoQuery]",e);els.status.textContent="No fue posible cargar las capas de GeoQuery.";els.list.innerHTML='<p class="placeholder-text">Revise que <strong>geoma/capas_geoquery</strong> esté disponible y vuelva a intentar.</p>'}}
  const backLink=document.getElementById("back-link");backLink.href=buildReturnUrl();backLink.addEventListener("click",e=>{if(history.length>1&&document.referrer){e.preventDefault();history.back()}});init();
})();
