(function(){
  "use strict";
  const MAX_LIMIT=20,CATALOG_URL="../capas_geoquery/catalogo.json",KML_COLOR="#00E5FF";
  const params=new URLSearchParams(location.search),queryLat=Number(params.get("lat")??params.get("queryLat")),queryLon=Number(params.get("lon")??params.get("queryLon"));
  const validPoint=Number.isFinite(queryLat)&&queryLat>=-90&&queryLat<=90&&Number.isFinite(queryLon)&&queryLon>=-180&&queryLon<=180;
  const queryMercator=validPoint?lonLatToMercator(queryLon,queryLat):null,scale=validPoint?Math.cos(queryLat*Math.PI/180):1;
  let allResults=[],ready=false;

  function lonLatToMercator(lon,lat){const x=lon*20037508.34/180;let y=Math.log(Math.tan((90+lat)*Math.PI/360))/(Math.PI/180);return[x,y*20037508.34/180]}
  function mercatorToLonLat(x,y){const lon=x/20037508.34*180;let lat=y/20037508.34*180;lat=180/Math.PI*(2*Math.atan(Math.exp(lat*Math.PI/180))-Math.PI/2);return[lon,lat]}
  function transform(c){if(!Array.isArray(c))return c;if(c.length>=2&&typeof c[0]==="number"&&typeof c[1]==="number")return mercatorToLonLat(c[0],c[1]);return c.map(transform)}
  function pointInRing(p,r){let inside=false,x=p[0],y=p[1];for(let i=0,j=r.length-1;i<r.length;j=i++){const xi=+r[i][0],yi=+r[i][1],xj=+r[j][0],yj=+r[j][1];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/((yj-yi)||Number.EPSILON)+xi))inside=!inside}return inside}
  function pointInPolygon(p,r){if(!r?.length||!pointInRing(p,r[0]))return false;for(let i=1;i<r.length;i++)if(pointInRing(p,r[i]))return false;return true}
  function nearestOnSeg(p,a,b){const px=p[0],py=p[1],ax=+a[0],ay=+a[1],bx=+b[0],by=+b[1],dx=bx-ax,dy=by-ay;if(!dx&&!dy)return{point:[ax,ay],sq:(px-ax)**2+(py-ay)**2};const t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy))),x=ax+t*dx,y=ay+t*dy;return{point:[x,y],sq:(px-x)**2+(py-y)**2}}
  function nearestOnPolygon(p,rings){if(pointInPolygon(p,rings))return{distance:0,point:p};let best={distance:Infinity,point:null};for(const r of rings||[]){for(let i=1;i<r.length;i++){const q=nearestOnSeg(p,r[i-1],r[i]);if(q.sq<best.distance){best={distance:q.sq,point:q.point}}}if(r.length>2){const q=nearestOnSeg(p,r[r.length-1],r[0]);if(q.sq<best.distance)best={distance:q.sq,point:q.point}}}return{distance:Math.sqrt(best.distance)*scale,point:best.point}}
  function geometryNearest(g){if(!g)return{distance:Infinity,point:null};if(g.type==="Polygon")return nearestOnPolygon(queryMercator,g.coordinates);if(g.type==="MultiPolygon"){let best={distance:Infinity,point:null};for(const p of g.coordinates){const q=nearestOnPolygon(queryMercator,p);if(q.distance<best.distance)best=q}return best}return{distance:Infinity,point:null}}
  function bboxDistance(b){if(!Array.isArray(b)||b.length<4)return Infinity;const[w,s,e,n]=b.map(Number),clon=Math.max(w,Math.min(e,queryLon)),clat=Math.max(s,Math.min(n,queryLat)),ml=(queryLat+clat)*Math.PI/360;return Math.hypot((queryLon-clon)*111320*Math.cos(ml),(queryLat-clat)*110540)}
  async function loadRegion(r){const u=`../capas_geoquery/${encodeURIComponent(r.file).replace(/%2F/g,"/")}`,res=await fetch(u,{cache:"force-cache"});if(!res.ok)throw new Error(`${r.region}: HTTP ${res.status}`);const g=await res.json();return Array.isArray(g.features)?g.features:[]}
  async function findNearest(catalog){const regions=(catalog.layers||[]).filter(l=>l.enabled!==false).map(l=>({...l,bboxDistance:bboxDistance(l.bbox)})).sort((a,b)=>a.bboxDistance-b.bboxDistance),nearest=[];for(const region of regions){const cutoff=nearest.length>=MAX_LIMIT?nearest[MAX_LIMIT-1].distance:Infinity;if(nearest.length>=MAX_LIMIT&&region.bboxDistance>cutoff)break;for(const feature of await loadRegion(region)){const near=geometryNearest(feature.geometry);if(Number.isFinite(near.distance))nearest.push({feature,distance:near.distance,nearestPoint:near.point,region:region.region})}nearest.sort((a,b)=>a.distance-b.distance);if(nearest.length>MAX_LIMIT)nearest.length=MAX_LIMIT}return nearest}
  function currentLimit(){return Number(document.querySelector('input[name="nearest-limit"]:checked')?.value)||5}
  function destinationPoint(lat,lon,distance,bearingDeg){const R=6371008.8,b=bearingDeg*Math.PI/180,p1=lat*Math.PI/180,l1=lon*Math.PI/180,d=distance/R,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(b)),l2=l1+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return[p2*180/Math.PI,l2*180/Math.PI]}
  function circleGeometry(radiusMeters,steps=128){const coords=[];for(let i=0;i<=steps;i++){const bearing=i*360/steps,[lat,lon]=destinationPoint(queryLat,queryLon,radiusMeters,bearing);coords.push([lon,lat])}return{type:"Polygon",coordinates:[coords]}}
  function label(f){const p=f.properties||{},n=String(p.Nombre||"").trim(),t=String(p.Tipo||"Masa de agua").trim()||"Masa de agua",c=String(p.Comuna||"").trim();return n||[t,c].filter(Boolean).join(" – ")||"Masa de agua sin nombre"}
  function localTimestamp(date=new Date()){return[date.getFullYear(),String(date.getMonth()+1).padStart(2,"0"),String(date.getDate()).padStart(2,"0"),String(date.getHours()).padStart(2,"0"),String(date.getMinutes()).padStart(2,"0"),String(date.getSeconds()).padStart(2,"0")].join("")}
  function style(extra={}){return{color:KML_COLOR,fillColor:KML_COLOR,opacity:1,fillOpacity:.18,weight:3,labelColor:KML_COLOR,labelScale:.9,...extra}}
  function unique(values){return[...new Set(values.map(v=>String(v??"").trim()).filter(Boolean))]}
  function summary(results){const areas=results.map(x=>Number(x.feature.properties?.st_area_sh)).filter(v=>Number.isFinite(v)&&v>0),totalArea=areas.reduce((a,b)=>a+b,0),meanPoi=results.length?results.reduce((s,x)=>s+x.distance,0)/results.length:NaN;return{totalArea,meanPoi,regions:unique(results.map(x=>x.region)),communes:unique(results.map(x=>x.feature.properties?.Comuna)),types:unique(results.map(x=>x.feature.properties?.Tipo))}}
  function buildState(){const results=allResults.slice(0,currentLimit()),registry=GeoQueryKmlExporter.createKmlExportRegistry(),radius=results.length?results[results.length-1].distance:NaN,stats=summary(results),folders=[{id:"query",name:"Punto consultado"},{id:"cluster",name:"Geometría del conjunto"},{id:"waters",name:"Masas de agua seleccionadas"}];
    GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:"geoma-query",site:"geoma",groupId:"general",role:"query-point",folderId:"query",type:"point",name:"Punto consultado",geometry:{type:"Point",coordinates:[queryLon,queryLat]},style:style({fillOpacity:1,weight:3,iconScale:1.1}),extendedData:{Latitud:queryLat.toFixed(6),Longitud:queryLon.toFixed(6),"Masas seleccionadas":results.length,"Regiones presentes":stats.regions.join(", "),"Comunas presentes":stats.communes.join(", ")},visible:true});
    if(Number.isFinite(radius)&&radius>0){
      GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:"geoma-container-circle",site:"geoma",groupId:"cluster",role:"cluster-circle",folderId:"cluster",type:"polygon",name:`Círculo envolvente · ${results.length} masas`,description:"Círculo envolvente definido por la distancia al borde de la masa seleccionada más lejana.",geometry:circleGeometry(radius),style:style({fillOpacity:.07,weight:3,fill:true,outline:true}),extendedData:{"Cantidad de masas":results.length,"Radio (km)":(radius/1000).toFixed(3),"Superficie total (ha)":(stats.totalArea/10000).toFixed(2),"Distancia media al POI (km)":Number.isFinite(stats.meanPoi)?(stats.meanPoi/1000).toFixed(3):"","Regiones":stats.regions.join(", "),"Comunas":stats.communes.join(", "),"Tipos de masa":stats.types.join(", ")},visible:true});
      const [edgeLat,edgeLon]=destinationPoint(queryLat,queryLon,radius,45);
      GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:"geoma-container-radius",site:"geoma",groupId:"cluster",role:"cluster-radius",folderId:"cluster",type:"line",name:"Radio del círculo envolvente",description:"Radio desde el punto consultado hasta el borde del círculo envolvente, equivalente a la distancia de la masa seleccionada más lejana.",geometry:{type:"LineString",coordinates:[[queryLon,queryLat],[edgeLon,edgeLat]]},style:style({weight:4,fill:false}),extendedData:{"Radio (km)":(radius/1000).toFixed(3),"Cantidad de masas":results.length,"Criterio":"Distancia al borde de la masa seleccionada más lejana"},visible:true});
    }
    results.forEach((item,index)=>{const p=item.feature.properties||{},area=Number(p.st_area_sh);GeoQueryKmlExporter.addUniqueKmlItem(registry,{id:`geoma-water-${index+1}`,site:"geoma",groupId:"waters",role:"water-polygon",folderId:"waters",type:String(item.feature.geometry?.type||"").toLowerCase()==="multipolygon"?"multipolygon":"polygon",name:`${index+1}. ${label(item.feature)}`,description:`${p.Tipo||"Masa de agua"}${p.Comuna?` · ${p.Comuna}`:""}${item.region?` · ${item.region}`:""}`,geometry:{type:item.feature.geometry.type,coordinates:transform(item.feature.geometry.coordinates)},style:style({fillOpacity:.22,weight:3,fill:true,outline:true}),extendedData:{Orden:index+1,Nombre:p.Nombre||"",Tipo:p.Tipo||"",Región:item.region||p.Region||p.Región||"",Comuna:p.Comuna||"","Superficie (ha)":Number.isFinite(area)?(area/10000).toFixed(2):"","Distancia al POI (km)":(item.distance/1000).toFixed(3),"Criterio de distancia":"Distancia mínima desde el POI al borde del polígono"},visible:true})});
    return{site:"geoma",fileName:`GeoMA_Consulta_${localTimestamp()}.kml`,documentName:"GeoQuery | GeoMA",documentDescription:`Consulta territorial de ${results.length} masas de agua más cercanas. Exporta las mismas geometrías visibles en el mapa: cuerpos de agua seleccionados, círculo envolvente y radio desde el POI al círculo.`,queryPoint:{lat:queryLat,lon:queryLon},folders,features:Array.from(registry.values())}}
  function refresh(){if(!ready)return;window.geoQueryState=window.geoQueryState||{};window.geoQueryState.mapExport=buildState();if(typeof window.geoQueryKmlRefresh==="function")window.geoQueryKmlRefresh()}
  async function init(){if(!validPoint||!window.GeoQueryKmlExporter)return;try{const r=await fetch(CATALOG_URL,{cache:"force-cache"});if(!r.ok)throw new Error(`Catálogo HTTP ${r.status}`);allResults=await findNearest(await r.json());ready=true;window.geoQueryState=window.geoQueryState||{};window.geoQueryState.mapExport=buildState();window.geoQueryKmlRefresh=GeoQueryKmlExporter.installGeoQueryKmlButton(()=>{refresh();return window.geoQueryState.mapExport});document.querySelectorAll('input[name="nearest-limit"]').forEach(el=>el.addEventListener("change",refresh))}catch(e){console.error("[GeoMA KML]",e)}}
  init();
})();
